blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import PostListView, PostDetailView, index

app_name = BlogConfig.name

urlpatterns = [
    path('list_posts', PostListView.as_view(), name='list_posts'),
    path('', index, name='index'),
    path('detail_post/<int:pk>/', PostDetailView.as_view(), name='detail_post'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls', namespace='user')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('sending/', include('sending.urls', namespace='sending')),
    path('', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sending/urls.py
from django.urls import path
from sending.apps import SendingConfig
from sending.views import CreateMessage, DetailMessage, ListMessages, UpdateMessage, DeleteMessage, ListSending, \
    CreateSending, DetailSending, UpdateSendingView, DeleteSendingView, DisableSendingView, ListTrySending

app_name = SendingConfig.name

urlpatterns = [
    path('create_message/', CreateMessage.as_view(), name='create_message'),
    path('detail_message/<int:pk>/', DetailMessage.as_view(), name='detail_message'),
    path('list_messages/', ListMessages.as_view(), name='list_messages'),
    path('update_message/<int:pk>/', UpdateMessage.as_view(), name='update_message'),
    path('delete_message/<int:pk>/', DeleteMessage.as_view(), name='delete_message'),
    path('delete_sending/<int:pk>/', DeleteSendingView.as_view(), name='delete_sending'),
    path('list_sending/', ListSending.as_view(), name='list_sending'),
    path('create_sending/', CreateSending.as_view(), name='create_sending'),
    path('detail_sending/<int:pk>/', DetailSending.as_view(), name='detail_sending'),
    path('update_sending/<int:pk>/', UpdateSendingView.as_view(), name='update_sending'),
    path('disable_sending/<int:pk>/', DisableSendingView.as_view(), name='disable_sending'),
    path('list_try_sending/', ListTrySending.as_view(), name='list_try_sending'),
]

sending/models.py
from datetime import datetime

from django.db import models

from customer.models import Customer
from user.models import User


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Создатель')
    theme = models.CharField(max_length=50, verbose_name='Тема')
    content = models.TextField(verbose_name='Контент')

    def __str__(self):
        return f'{self.theme}'

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class Sending(models.Model):
    ONE_A_DAY = 'раз в день'
    ONE_A_WEEK = 'раз в неделю'
    ONE_A_MONTH = 'раз в месяц'

    INTERVAL = (
        (ONE_A_DAY, 'раз в день'),
        (ONE_A_WEEK, 'раз в неделю'),
        (ONE_A_MONTH, 'раз в месяц')
    )
    COMPLITED = 'Завершена'
    CREATED = 'Создана'
    ACTIVATED = 'Запущена'

    STATUS = (
        (COMPLITED, 'завершена'),
        (CREATED, 'создана'),
        (ACTIVATED, 'активирована')
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Создатель')
    customer = models.ManyToManyField(Customer, verbose_name='Клиент')
    message = models.ForeignKey(Message, on_delete=models.SET_NULL, verbose_name='Сообщение', null=True)
    created_at = models.DateTimeField(editable=True, auto_now=True, verbose_name='Время создания')
    updated_at = models.DateTimeField(editable=True, auto_now=True, verbose_name='Время обновления')
    next_run = models.DateTimeField(editable=True, auto_now=True, verbose_name='Дата следующей рассылки')
    interval = models.CharField(choices=INTERVAL, max_length=30, verbose_name='Периодичность')
    status_sending = models.CharField(choices=STATUS, max_length=30, verbose_name='Статус')
    start_sending_date = models.DateField(default=datetime.today(), verbose_name='Дата начала')
    start_sending_time = models.TimeField(default=datetime.now().time(), verbose_name='время рассылки', blank=True,
                                          null=True)

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'

        permissions = [
            (
                'can_view_sending',
                'Can view sending'
            ),
            (
                'can_disable_sending',
                'Can disable sending'
            )
        ]

    def get_customer(self):
        return ','.join([str(cus) for cus in self.customer.all()])


class TrySending(models.Model):
    STATUS_CHOICES = [
        ('success', 'завершена'),
        ('failure', 'провалена'),
        ('in_progress', 'в процессе'),
    ]

    sending = models.ForeignKey(Sending, on_delete=models.CASCADE, verbose_name='Письмо', blank=True, null=True)
    last_attempt = models.DateTimeField(auto_now_add=True, verbose_name='Дата последней попытки')
    status_attempt = models.CharField(choices=STATUS_CHOICES, max_length=30, default='in_progress',
                                      verbose_name='Текущий статус')
    answer_server = models.CharField(max_length=20, verbose_name='Ответ почтового сервера')

    class Meta:
        verbose_name = 'Попытка рассылки'
        verbose_name_plural = 'Попытки рассылок'

sending/forms.py
from datetime import datetime

from django import forms
from django.forms import DateTimeInput

from customer.models import Customer
from sending.models import Message, Sending


class MessageForm(forms.ModelForm):
    theme = forms.CharField(max_length=50, min_length=4, required=True, help_text='Required: First Name',
                            widget=forms.TextInput(
                                attrs={'class': 'form-control', 'placeholder': 'Тема'}))
    content = forms.CharField(max_length=200, min_length=4, required=True,
                              widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Контент'}))

    class Meta:
        model = Message
        fields = ('theme', 'content')


class CreateSendingForm(forms.ModelForm):
    class Meta:
        model = Sending
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)
        self.fields['customer'].queryset = Customer.objects.all()
        self.fields['message'].queryset = Message.objects.filter(
            user=self.request)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class DisableSendingForm(forms.ModelForm):

    class Meta:
        model = Sending
        fields = ('status_sending',)

class UpdateSendingForm(forms.ModelForm):

    class Meta:
        model = Sending
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(UpdateSendingForm, self).__init__(*args, **kwargs)
        self.fields['user'].widget.attrs['readonly'] = True

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

sending/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView

from sending.forms import MessageForm, CreateSendingForm, UpdateSendingForm, DisableSendingForm
from sending.models import Message, Sending, TrySending


class CreateMessage(CreateView):
    model = Message
    template_name = 'sending/create_message.html'
    success_url = 'sending:list_messages'
    form_class = MessageForm
    extra_context = {
        'title': 'Создание письма'
    }

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        form.user = self.request.user
        if form.is_valid():
            message = form.save(commit=False)
            message.user = request.user
            message.save()
            return HttpResponseRedirect(reverse(self.success_url))
        return render(request, self.template_name)


class ListMessages(ListView):
    model = Message
    template_name = 'sending/list_messages.html'
    extra_context = {
        'title': 'Список писем'
    }


class DetailMessage(DetailView):
    model = Message
    template_name = 'sending/detail_message.html'
    extra_context = {
        'title': 'Информация о письме'
    }

    def get_object(self, queryset=None):
        message = get_object_or_404(Message, pk=self.kwargs['pk'])
        return message


class UpdateMessage(PermissionRequiredMixin, UpdateView):
    permission_required = 'sending.change_message'
    model = Message
    template_name = 'sending/update_message.html'
    form_class = MessageForm
    extra_context = {
        'title': 'Обновление информации о письме'
    }

    def form_valid(self, form):
        super().form_valid(form)
        form.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse_lazy('sending:detail_message', kwargs={'pk': self.kwargs['pk']})


class DeleteMessage(DeleteView):
    model = Message
    success_url = reverse_lazy('sending:list_messages')
    extra_context = {
        'title': 'Информация о письме'
    }


class ListSending(ListView):
    model = Sending
    template_name = 'sending/list_sending.html'
    extra_context = {
        'title': 'Список рассылок'
    }

    def get_queryset(self):

        if not self.request.user.has_perm('sending.can_view_sending'):
            return Sending.objects.filter(user=self.request.user)
        else:
            return Sending.objects.all()


class DisableSendingView(PermissionRequiredMixin, UpdateView):
    permission_required = 'sending.can_disable_sending'
    model = Sending
    form_class = DisableSendingForm
    success_url = reverse_lazy('sending:list_sending')
    template_name = 'sending/disable.html'

    def post(self, request, *args, **kwargs):
        if self.request.method == 'POST':
            sending_object = Sending.objects.get(id=kwargs['pk'])
            sending_object.status_sending = Sending.COMPLITED
            sending_object.save()
            return HttpResponseRedirect(reverse('sending:list_sending'))


class CreateSending(CreateView):
    model = Sending
    template_name = 'sending/create_sending.html'
    form_class = CreateSendingForm
    success_url = reverse_lazy('sending:list_sending')
    extra_context = {
        'title': 'Создание рассылки'
    }

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save(commit=False)
            self.object.user = self.request.user
            self.object.save()
            return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'request': self.request.user})
        return kwargs


class UpdateSendingView(PermissionRequiredMixin, UpdateView):
    permission_required = 'sending.change_sending'
    model = Sending
    template_name = 'sending/update_sending.html'
    form_class = UpdateSendingForm
    extra_context = {
        'title': 'Обновление информации о рассылке'
    }

    def form_valid(self, form):
        if self.request.method == 'POST':
            form = UpdateSendingForm(data=self.request.POST, instance=self.request.user)
            if form.is_valid():
                form.instance = self.object
                form.updated_at = timezone.now()
                form.save()
        else:
            form = UpdateSendingForm(instance=self.request.user)

        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('sending:detail_sending', kwargs={'pk': self.kwargs['pk']})


class DetailSending(PermissionRequiredMixin, DetailView):
    permission_required = 'sending.can_view_sending'
    model = Sending
    template_name = 'sending/detail_sending.html'
    extra_context = {
        'title': 'Информация о рассылке'
    }

    def get_object(self, queryset=None):
        sending = Sending.objects.get(pk=self.kwargs['pk'])
        return sending


class DeleteSendingView(DeleteView):
    model = Sending
    extra_context = {
        'title': 'Удаление рассылки'
    }

    def get_success_url(self):
        return reverse_lazy('sending:list_sending')


class ListTrySending(ListView):
    model = TrySending
    template_name = 'sending/list_try_sending.html'
    extra_context = {
        'title': 'Статистика по рассылкам'
    }

    def get_queryset(self):
        return TrySending.objects.all()

sending/templates/sending/create_message.html
{% extends 'user/base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}

    <div class="container">
      <h4 class="text-lg-start">Создание письма</h4>
    <form action="{% url 'sending:create_message' %}" method="post">
        {% csrf_token %}
        <div class="form-row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.theme.id_for_label }}">Тема</label>
                    {{ form.theme }}
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.content.id_for_label }}">Контент</label>
                    {{ form.content }}
                </div>
            </div>
        </div>
        <div class="form-group mt-4 mb-0">
            <input class="btn btn-primary btn-block" type="submit" value="Создать письмо">
        </div>
    </form>
    </div>
{% endblock %}

sending/templates/sending/create_sending.html
{% extends 'user/base.html' %}

{% block title %} {{ title }} {% endblock %}


{% block content %}

    <div class="container">
        <form action="{% url 'sending:create_sending' %}" method="post">
            {% csrf_token %}

            {{ form.as_table }}

{#            <div class="form-row">#}
{#                <div class="col-md-6">#}
{#                    <div class="form-group">#}
{#                        <label class="small mb-lg-2" for="{{ form.customer.id_for_label }}">Клиенты</label>#}
{#                        {{ form.customer }}#}
{#                    </div>#}
{#                </div>#}
{#                <div class="col-md-6">#}
{#                    <div class="form-group">#}
{#                        <label class="small mb-1" for="{{ form.message.id_for_label }}">Письмо</label>#}
{#                        {{ form.message }}#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{##}
{##}
{##}
{#            <div class="form-row">#}
{#                <div class="col-md-6">#}
{#                    <div class="form-group">#}
{#                        <label class="small mb-1" for="{{ form.interval.id_for_label }}">Интервал</label>#}
{#                        {{ form.interval }}#}
{#                    </div>#}
{#                </div>#}
{#                <div class="col-md-6">#}
{#                    <div class="form-group">#}
{#                        <label class="small mb-1" for="{{ form.status_sending.id_for_label }}">Статус</label>#}
{#                        {{ form.status_sending }}#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#           #}
{#            <div class="form-row">#}
{#                <br>#}
{#                Старт рассылки#}
{#            <div class="input-group date" id="datetimepicker1" data-target-input="nearest">#}
{##}
{#                {{ form.start_sending }}#}
{#                <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">#}
{#                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>#}
{#                </div>#}
{#            </div>#}
{#            </div>#}
{#             <div class="form-row">#}
{##}
{#            </div>#}
{##}
{#            <script>#}
{#                $(function () {#}
{#                    $("#datetimepicker1").datetimepicker({#}
{#                        format: 'DD/MM/YYYY HH:mm',#}
{#                    });#}
{#                });#}
{#            </script>#}

            <div class="form-group mt-4 mb-0">
                <input class="btn btn-primary btn-block" type="submit" value="Создать рассылку">
            </div>
        </form>
    </div>

{% endblock %}

sending/templates/sending/detail_message.html
{% extends 'user/base.html' %}

{% block title %} {{ title }} {% endblock %}

{%  block content %}
    <div class="container">
{#    {% if perms.message.view_message %}#}

   <div class="row text-center">
                <div class="col-6">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <h4 class="my-0 font-weight-normal">{{ object.theme }}</h4>
                        </div>

                        <div class="card-body">


                            <p class="bg-light">{{ object.content }}</p>
                        </div>
                    </div>
                </div>
            </div>

    </div>
{#    {% else %}#}
{#        У вас нет прав#}
{#    {% endif %}#}
{% endblock %}

sending/templates/sending/detail_sending.html
{% extends 'user/base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
    <div class="container">

        <div class="row text-center">
            <div class="col-6">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Создатель рассылки: {{ object.user }}</h4>
                    </div>

                    <div class="card-body">


                        <ul class="list-unstyled mt-3 mb-4 text-start m-3 btn-group-vertical">

                            <ol>
                                <h4>Список клиентов:</h4>
                                {% for client in object.customer.all %}
                                    <li>{{ client.first_name }}</li>
                                {% endfor %}
                            </ol>
                            <br>

                            <li>Тема письма: {{ object.message.theme }}</li>
                            <li>Интервал: {{ object.interval }}</li>
                            <li>Статус: {{ object.status_sending }}</li>
                            <li>Дата рассылки: {{ object.start_sending_date }}</li>
                            <li>Время рассылки: {{ object.start_sending_time }}</li>
                            <li>Создание рассылки: {{ object.created_at }}</li>
                            <li>Обновление рассылки: {{ object.updated_at }}</li>

                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

sending/templates/sending/disable.html
{% extends 'user/base.html' %}

{% block title %} {{ title }} {% endblock %}


{% block content %}
    <div class="container">
        <h1 class="text-warning">Отключение рассылки</h1>
        <form method="POST">
            {% csrf_token %}
            <table>
            Подтверждаете отключение {{ object.status_sending }}?
            </table>
            <input class="btn-danger" type="submit" value="Отключить">
            <a type="button" href="{% url 'sending:list_sending' %}"
               class="btn btn-lg btn-block btn-link">Назад</a>
        </form>
    </div>
{% endblock %}

sending/templates/sending/list_messages.html
{% extends 'user/base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
    <div class="container">
        {% for object in object_list %}
            <div class="row text-center">
                <div class="col-6">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <h4 class="my-0 font-weight-normal">{{ object.theme }}</h4>
                        </div>
                        <div class="card-body">
                            <p class="bg-light">{{ object.content }}</p>
                            <a type="button" href="{% url 'sending:detail_message' object.id %}"
                               class="btn btn-lg btn-block btn-outline-primary">Детализация</a>
                            {% if perms.sending.can_change_message %}
                                <a type="button" href="{% url 'sending:update_message' object.id %}"
                                   class="btn btn-lg btn-block btn-outline-danger">Изменить</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

sending/templates/sending/list_sending.html
{% extends 'user/base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
    <div class="container">
        <h1 class="text-body">Список рассылок</h1>
        {% for object in object_list %}
            <div class="row text-center">
                <div class="col-6">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <h4 class="my-0 font-weight-normal">{{ object.message.theme }}</h4>
                        </div>

                        <div class="card-body">


                            <ul class="list-unstyled mt-3 mb-4 text-start m-3 bg-light">
                                <li>Дата: {{ object.start_sending_date}}</li>
                                <li>Время: {{ object.start_sending_time }}</li>
                                <li>Создатель: {{ object.user }}</li>
                                <li>Интервал: {{ object.interval }}</li>
                                <li>Статус: {{ object.status_sending }}</li>

                            </ul>

                            <a type="button" href="{% url 'sending:detail_sending' object.id %}"
                               class="btn btn-lg btn-block btn-outline-primary">Детализация</a>
                            {% if perms.sending.can_change_sending %}
                                <a type="button" href="{% url 'sending:update_sending' object.id %}"
                                   class="btn btn-lg btn-block btn-outline-danger">Изменить</a>
                            {% endif %}
                            {% if object.status_sending != 'Завершена' %}
                                <a type="button" href="{% url 'sending:disable_sending' object.id %}"
                                   class="btn btn-lg btn-block btn-outline-danger">Отключить рассылку</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

sending/templates/sending/list_try_sending.html
 {% extends 'user/base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
    <div class="container">
        <h1 class="text-body">Отчет о рассылках</h1>
        {% for object in object_list %}
            <div class="row text-center">
                <div class="col-6">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <h4 class="my-0 font-weight-normal">{{ object.message.theme }}</h4>
                        </div>
                        <div class="card-body">
                            <ul class="list-unstyled mt-3 mb-4 text-start m-3 bg-light">
                                <li>Тема письма: {{ object.sending.message}}</li>
                                <li>Статус: {{ object.status_attempt }}</li>
                                <li>Последняя попытка: {{ object.last_attempt }}</li>
                                <li>Ответ сервера: {{ object.answer_server }}</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

sending/templates/sending/message_confirm_delete.html
{% extends 'user/base.html' %}

{% block title %} {{ title }} {% endblock %}


{% block content %}
    <div class="container">
        <h1 class="text-warning">Удаление письма</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <table>
            Подтверждаете удаление {{ object.theme }}?
            </table>
            <input class="btn-danger" type="submit" value="Удалить">
            <a type="button" href="{% url 'sending:detail_message' object.id %}"
               class="btn btn-lg btn-block btn-link">Назад</a>
        </form>
    </div>
{% endblock %}

sending/templates/sending/sending_confirm_delete.html
{% extends 'user/base.html' %}

{% block title %} {% endblock %}

{% block content %}
    <div class="container">
        <h1 class="text-warning">Подтверждение удаления</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <table>
            Подтверждаете удаление {{ object.message }}?
            </table>
            <input class="btn-danger" type="submit" value="Удалить">
        </form>
    <a type="button" href="{% url 'sending:update_sending' object.id %}"
               class="btn btn-lg btn-block btn-link">Назад</a>
    </div>
{% endblock %}

sending/templates/sending/update_message.html
{% extends 'user/base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}

      <div class="container">
    <form action="{% url 'sending:update_message' object.id %}" method="post">
        {% csrf_token %}
        <div class="form-row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.theme.id_for_label }}">Тема</label>
                    {{ form.theme }}
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.content.id_for_label }}">Контент</label>
                    {{ form.content }}
                </div>
            </div>
        </div>
        <div class="form-group mt-4 mb-0">
            <input class="btn btn-primary btn-block" type="submit" value="Обновить данные">
        </div>

        <a type="button" href="{% url 'sending:delete_message' object.id %}"
                               class="btn btn-lg btn-block btn-danger">Удалить</a>
    </form>
    </div>

{% endblock %}

sending/templates/sending/update_sending.html
{% extends 'user/base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}

    <div class="container">
        <form action="{% url 'sending:update_sending' object.id %}" method="post">
            {% csrf_token %}
            {{ form.as_table }}
            <div class="form-group mt-4 mb-0">
                <input class="btn btn-primary btn-block" type="submit" value="Обновить данные">
            </div>
            <a type="button" href="{% url 'sending:delete_sending' object.id %}"
               class="btn btn-lg btn-block btn-danger">Удалить</a>
        </form>
    </div>
{% endblock %}