blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import PostListView, PostDetailView, index

app_name = BlogConfig.name

urlpatterns = [
    path('list_posts', PostListView.as_view(), name='list_posts'),
    path('', index, name='index'),
    path('detail_post/<int:pk>/', PostDetailView.as_view(), name='detail_post'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls', namespace='user')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('sending/', include('sending.urls', namespace='sending')),
    path('', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from customer.views import CreateCustomer, ListCustomers, DetailCustomer, UpdateCustomer, DeleteCustomerView

app_name = 'customer'

urlpatterns = [
    path('create_customer/', CreateCustomer.as_view(), name='create_customer'),
    path('list_customers/', ListCustomers.as_view(), name='list_customers'),
    path('detail_customer/<int:pk>/', cache_page(60)(DetailCustomer.as_view()), name='detail_customer'),
    path('update_customer/<int:pk>/', UpdateCustomer.as_view(), name='update_customer'),
    path('delete_customer/<int:pk>/', DeleteCustomerView.as_view(), name='delete_customer'),
]

customer/models.py
from django.db import models
from user.models import User


class Customer(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Создатель', blank=True, null=True)
    first_name = models.CharField(max_length=20, verbose_name='Имя')
    last_name = models.CharField(max_length=20, verbose_name='Фамилия')
    email = models.EmailField(unique=True, verbose_name='Почта клиента')
    comment = models.TextField(verbose_name='Коментарий')

    def __str__(self):
        return f'{self.first_name} || {self.last_name}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'

        permissions = {
            ('can_view_customers', 'Can view customers')
        }

customer/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.core.exceptions import ValidationError
from validate_email import validate_email

from customer.models import Customer


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('first_name', 'last_name', 'email', 'comment')

    def __init__(self, *args, **kwargs):
        super(CustomerForm, self).__init__(*args, **kwargs)

        for filed_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'

    def clean_email(self):
        new_email = self.cleaned_data['email']
        if Customer.objects.filter(email=new_email).exists():
            raise ValidationError('Почта занята')
        if validate_email(new_email, verify=True) == None:
            raise ValidationError('Почты не существует')
        return new_email


class UpdateCustomerForm(UserChangeForm):
    class Meta:
        model = Customer
        fields = ('first_name', 'last_name', 'email', 'comment')

    def __init__(self, *args, **kwargs):
        super(UpdateCustomerForm, self).__init__(*args, **kwargs)
        # self.fields['creator'].widget.attrs['readonly'] = True
        self.fields['email'].widget.attrs['readonly'] = True

        for filed_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'

customer/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from customer.forms import CustomerForm, UpdateCustomerForm
from customer.models import Customer
from customer.services import get_customers
from user.models import User


class CreateCustomer(CreateView):
    model = Customer
    template_name = 'customer/create_customer.html'
    form_class = CustomerForm
    success_url = reverse_lazy('customer:list_customers')
    extra_context = {
        'title': 'Создание клиента'
    }

    def form_valid(self, form):
        form = CustomerForm(data=self.request.POST)
        if form.is_valid():
            customer = form.save(commit=False)
            customer.creator = self.get_object()
            customer.save()
            return super().form_valid(form)

    def get_object(self, queryset=None):
        creator = User.objects.get(pk=self.request.user.pk)
        return creator

class ListCustomers(ListView):

    model = Customer
    template_name = 'customer/list_customers.html'
    extra_context = {
        'title': 'Список клиентов'
    }
    def get_queryset(self):
        if self.request.user.has_perm('customer.can_view_customers'):
            return get_customers()
        else:
            return Customer.objects.filter(creator=self.request.user)

class DetailCustomer(DetailView):
    model = Customer
    template_name = 'customer/detail.html'
    extra_context = {
        'title': 'Информация о клиенте'
    }
    def get_object(self, queryset=None):
        return Customer.objects.get(id=self.kwargs['pk'])

class UpdateCustomer(UpdateView):
    model = Customer
    template_name = 'customer/update_customer.html'
    form_class = UpdateCustomerForm
    extra_context = {
        'title': 'Обновление информации о клиенте'
    }

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        return context


    def form_valid(self, form):
        super().form_valid(form)
        form.save()
        return HttpResponseRedirect(self.get_success_url())


    def get_success_url(self):
        return reverse_lazy('customer:detail_customer', kwargs={'pk': self.kwargs['pk']})


class DeleteCustomerView(DeleteView):
    model = Customer
    success_url = reverse_lazy('customer:list_customers')

customer/templates/customer/create_customer.html
{% extends 'user/base.html' %}

{% block title %} {{ title }} {% endblock %}

{%  block content %}
      <div class="container">
      <h4>Создание клиента</h4>
    <form action="{% url 'customer:create_customer' %}" method="post">
        {% csrf_token %}
        {{ form.as_table }}
{##}
{#        <div class="form-row">#}
{#            <div class="col-md-6">#}
{#                <div class="form-group">#}
{#                    <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>#}
{#                    {{ form.first_name }}#}
{#                </div>#}
{#            </div>#}
{#            <div class="col-md-6">#}
{#                <div class="form-group">#}
{#                    <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>#}
{#                    {{ form.last_name }}#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#        <div class="form-row">#}
{##}
{#            <div class="col-md-6">#}
{#                <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной#}
{#                    почты</label>#}
{#                {{ form.email }}#}
{#            </div>#}
{#             <div class="col-md-6">#}
{#                <label class="small mb-1" for="{{ form.comment.id_for_label }}">Коментарий</label>#}
{#                {{ form.comment }}#}
{#            </div>#}
{#        </div>#}


        <div class="form-group mt-4 mb-0">
            <input class="btn btn-primary btn-block" type="submit" value="Создать клиента">
        </div>
    </form>
    </div>
{% endblock %}

customer/templates/customer/customer_confirm_delete.html
{% extends 'user/base.html' %}

{% block content %}
<div class="col">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Удаление клиента</h5>
      <form method="post">
        {% csrf_token %}
        Уверены, что хотите удалить клиента "{{ object.username }}"?<br>
        <input type="submit" class="btn btn-outline-danger" value="Уверен">
      </form>
      <div class="card-footer">
        <a href="{% url 'customer:list_customers' %}" class="btn btn-primary"><< Назад</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

customer/templates/customer/detail.html
{% extends 'user/base.html' %}

{% block title %} {{ title }} {% endblock %}

{%  block content %}
    <div class="container">

   <div class="row text-center">
                <div class="col-12">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <h4 class="my-0 font-weight-normal">{{ object.first_name }}</h4>
                        </div>

                        <div class="card-body">


                            <ul class="list-unstyled mt-3 mb-4 text-center m-3 bg-light" >
                                <li>Фамилия: {{ object.last_name}}</li>
                                <li>Почта: {{ object.email}}</li>
                                <li>Создатель: {{ object.creator}}</li>

                            </ul>
                        </div>
                    </div>
                </div>
            </div>

    </div>
{% endblock %}

customer/templates/customer/list_customers.html
{% extends 'user/base.html' %}

{% block title %} {{ title }} {% endblock %}

{%  block content %}
    <div class="container">
 {% for object in object_list %}
   <div class="row text-center">
                <div class="col-12">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <h4 class="my-0 font-weight-normal">{{ object.first_name }}</h4>
                        </div>

                        <div class="card-body">


                            <ul class="list-unstyled mt-3 mb-4 text-center m-3 bg-light" >
                                <li>Фамилия: {{ object.last_name}}</li>
                                <li>Почта: {{ object.email}}</li>
                                <li>Создатель: {{ object.creator}}</li>

                            </ul>

                            <a type="button" href="{% url 'customer:detail_customer' object.id %}"
                               class="btn btn-lg btn-block btn-outline-primary">Детализация</a>
                             <a type="button" href="{% url 'customer:update_customer' object.id %}"
                               class="btn btn-lg btn-block btn-outline-danger">Изменить</a>
                        </div>
                    </div>
                </div>
            </div>
    {% endfor %}
    </div>
{% endblock %}

customer/templates/customer/update_customer.html
{% extends 'user/base.html' %}

{% block title %} {{ title }} {% endblock %}

{%  block content %}
      <div class="container">
    <form action="{% url 'customer:update_customer' object.pk %}" method="post">
        {% csrf_token %}

        <div class="form-row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                    {{ form.first_name }}
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                    {{ form.last_name }}
                </div>
            </div>
        </div>
        <div class="form-row">

            <div class="col-md-6">
                <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                    почты</label>
                {{ form.email }}
            </div>
             <div class="col-md-6">
                <label class="small mb-1" for="{{ form.comment.id_for_label }}">Коментарий</label>
                {{ form.comment }}
            </div>
        </div>


        <div class="form-group mt-4 mb-0">
            <input class="btn btn-primary btn-block" type="submit" value="Изменить данные">
        </div>
        <a type="button" href="{% url 'customer:delete_customer' object.id %}"
                               class="btn btn-lg btn-block btn-danger">Удалить</a>
    </form>
    </div>
{% endblock %}