blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import PostListView, PostDetailView, index

app_name = BlogConfig.name

urlpatterns = [
    path('list_posts', PostListView.as_view(), name='list_posts'),
    path('', index, name='index'),
    path('detail_post/<int:pk>/', PostDetailView.as_view(), name='detail_post'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls', namespace='user')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('sending/', include('sending.urls', namespace='sending')),
    path('', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=30, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Содержание')
    image = models.ImageField(upload_to='blog', verbose_name='Изображение', blank=True, null=True)
    count_views = models.IntegerField(default=0, verbose_name='Количество просмотров')
    date_published = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from blog.models import Blog
from blog.services import get_posts
from customer.models import Customer
from sending.models import Sending


class PostListView(ListView):
    model = Blog
    template_name = 'blog/list_blogs.html'


class PostDetailView(DetailView):
    model = Blog
    template_name = 'blog/detail_post.html'

    def get_object(self, queryset=None):
        object = Blog.objects.get(pk=self.kwargs['pk'])
        if object:
            object.count_views += 1
            object.save()
        return object

def index(request):
    context = {
        'posts': get_posts()[:3],
        'title': 'Главная страница',
        'all_sending': Sending.objects.all().count(),
        'sending': Sending.objects.filter(status_sending=Sending.ACTIVATED).count(),
        'unique_customers': Customer.objects.all().count()
    }
    return render(request, 'blog/index.html', context)

blog/templates/blog/detail_post.html
{% extends 'user/base.html' %}

{% block title %} {{ title }} {% endblock %}

{%  block content %}
<div class="container">
    {% if object.image %}
    <img class="card-img-top" src="{{ object.image.url }}" alt="img" height="700">
    {% endif %}
    <div class="row text-center">
        <div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-center m-3 bg-light">
                        <li>Текст поста: {{ object.content}}</li>
                        <li>Количество просмотров: {{ object.count_views}}</li>
                        <li>Дата публикации: {{ object.date_published }}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'user/base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
    <h1 class="text-center">Главная страница</h1>
    <br>
    <div class="container overflow-hidden">
        <div class="row gy-5">
            <div class="col-6">
                {% for post in posts %}
                    <div class="p-3 border bg-light">{{ post.title }}</div>
                    {% if post.image %}
                        <img class="card-img-top" src="{{ post.image.url }}" alt="img" height="350" width="100"><br>
                        <a type="button" href="{% url 'blog:detail_post' post.id %}"
                               class="btn btn-lg btn-block btn-outline-primary">Детальная информация</a>
                    {% endif %}
                {% endfor %}
            </div>
            <div class="col-6">
                <div class="p-3 border bg-light">Количество рассылок: {{ all_sending }}</div>
                <div class="p-3 border bg-light">Количество активных рассылок: {{ sending }}</div>
                <div class="p-3 border bg-light">Количество клиентов: {{ unique_customers }}</div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/list_blogs.html
{% extends 'user/base.html' %}

{% block title %} {{ title }} {% endblock %}

{%  block content %}
    <div class="container">
    {% for object in object_list %}
    <div class="row text-center">
                <div class="col-6">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                        </div>
                         {% if object.image %}
                            <img class="card-img-top" src="{{ object.image.url }}" alt="img" height="350" width="100">
                        {% endif %}
                        <a type="button" href="{% url 'blog:detail_post' object.id %}"
                               class="btn btn-lg btn-block btn-outline-primary">Детальная информация</a>
                    </div>
                </div>
            </div>
    {% endfor %}
    </div>
{% endblock %}