blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import PostListView, PostDetailView, index

app_name = BlogConfig.name

urlpatterns = [
    path('list_posts', PostListView.as_view(), name='list_posts'),
    path('', index, name='index'),
    path('detail_post/<int:pk>/', PostDetailView.as_view(), name='detail_post'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls', namespace='user')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('sending/', include('sending.urls', namespace='sending')),
    path('', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from customer.views import CreateCustomer, ListCustomers, DetailCustomer, UpdateCustomer, DeleteCustomerView

app_name = 'customer'

urlpatterns = [
    path('create_customer/', CreateCustomer.as_view(), name='create_customer'),
    path('list_customers/', ListCustomers.as_view(), name='list_customers'),
    path('detail_customer/<int:pk>/', cache_page(60)(DetailCustomer.as_view()), name='detail_customer'),
    path('update_customer/<int:pk>/', UpdateCustomer.as_view(), name='update_customer'),
    path('delete_customer/<int:pk>/', DeleteCustomerView.as_view(), name='delete_customer'),
]

sending/urls.py
from django.urls import path
from sending.apps import SendingConfig
from sending.views import CreateMessage, DetailMessage, ListMessages, UpdateMessage, DeleteMessage, ListSending, \
    CreateSending, DetailSending, UpdateSendingView, DeleteSendingView, DisableSendingView, ListTrySending

app_name = SendingConfig.name

urlpatterns = [
    path('create_message/', CreateMessage.as_view(), name='create_message'),
    path('detail_message/<int:pk>/', DetailMessage.as_view(), name='detail_message'),
    path('list_messages/', ListMessages.as_view(), name='list_messages'),
    path('update_message/<int:pk>/', UpdateMessage.as_view(), name='update_message'),
    path('delete_message/<int:pk>/', DeleteMessage.as_view(), name='delete_message'),
    path('delete_sending/<int:pk>/', DeleteSendingView.as_view(), name='delete_sending'),
    path('list_sending/', ListSending.as_view(), name='list_sending'),
    path('create_sending/', CreateSending.as_view(), name='create_sending'),
    path('detail_sending/<int:pk>/', DetailSending.as_view(), name='detail_sending'),
    path('update_sending/<int:pk>/', UpdateSendingView.as_view(), name='update_sending'),
    path('disable_sending/<int:pk>/', DisableSendingView.as_view(), name='disable_sending'),
    path('list_try_sending/', ListTrySending.as_view(), name='list_try_sending'),
]

user/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.views.decorators.cache import cache_page
from user.apps import UserConfig
from user.views import RegisterUser, ProfileUser, confirm_code, DeleteUserView, ListUsersView, BlockUser

app_name = UserConfig.name

urlpatterns = [
    path('register', RegisterUser.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='user/login.html'), name='login'),
    path('profile/', cache_page(60)(ProfileUser.as_view()), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('list_users/', ListUsersView.as_view(), name='list_users'),
    path('delete/<int:pk>/', DeleteUserView.as_view(), name='delete'),
    path('confirm_code/<str:email>/', confirm_code, name='confirm_code'),
    path('blocked_user/<int:pk>/', BlockUser.as_view(), name='blocked_user'),
]

user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None
    email = models.EmailField(max_length=30, unique=True, verbose_name='Почта')
    verify_code = models.CharField(max_length=10, unique=True, verbose_name='Код верификации')
    avatar = models.ImageField(upload_to='users', verbose_name='аватар', blank=True, null=True)
    phone = models.CharField(max_length=20, verbose_name='Номер телефона', blank=True, null=True)
    is_active = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return f'{self.email}'

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

        permissions = {
            ('can_blocked_user', 'Can blocked user')
        }

user/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=12, min_length=4, required=True, help_text='Required: First Name',
                                 widget=forms.TextInput(
                                     attrs={'class': 'form-control', 'placeholder': 'Имя'}))
    last_name = forms.CharField(max_length=12, min_length=4, required=True, help_text='Required: Last Name',
                                widget=(forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Фамилия'})))
    email = forms.EmailField(max_length=50, help_text='Required. Inform a valid email address.',
                             widget=(forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Email'})))
    password1 = forms.CharField(label=_('Password'),
                                widget=(forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Пароль'})),
                                help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label=_('Password Confirmation'),
                                widget=forms.PasswordInput(
                                    attrs={'class': 'form-control', 'placeholder': 'Повторите пароль'}),
                                help_text=_('Just Enter the same password, for confirmation'))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'password1', 'password2',)


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'phone', 'avatar')
        exclude = ('password',)

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs['readonly'] = True
        self.fields['password'].widget.attrs['hidden'] = True

        for filed_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'


class UserBlockedForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('is_active',)

user/views.py
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView
from django.views.generic import UpdateView, DeleteView, ListView

from config import settings
from user.forms import UserRegisterForm, UserProfileForm, UserBlockedForm
from user.models import User
from user.services import get_users
from user.utils import generate_code


class RegisterUser(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'user/register.html'
    extra_context = {
        'title': 'Регистрация'
    }

    def get_success_url(self):
        return reverse('user:confirm_code', kwargs={'email': self.object.email})

    def form_valid(self, form):
        if form.is_valid():
            new_user = form.save(commit=False)
            code = generate_code()
            new_user.verify_code = code
            new_user.save()
            send_mail(
                subject='Вы зарегистрировались',
                message=code,
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[new_user.email]
            )

        return super().form_valid(form)


def confirm_code(request, email):
    if request.method == 'POST':
        verify_code = request.POST.get('verify_code')
        user = User.objects.get(email=email)
        if user.verify_code == verify_code:
            user.is_active = True
            user.save()
            return redirect(reverse('user:login'))
        else:
            raise ValidationError(f'You have used the wrong code!')
    else:
        context = {'title': 'Подтверждение почты'}

    return render(request, 'user/confirm_code.html', context)


class ProfileUser(UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'user/profile.html'
    success_url = reverse_lazy('user:profile')
    extra_context = {
        'title': 'Профиль'
    }

    def get_success_url(self):
        return reverse_lazy('user:profile', kwargs={'pk': self.kwargs['pk']})

    def post(self, request, *args, **kwargs):
        form = UserProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
        return redirect(self.success_url)

    def get_object(self, queryset=None):
        return User.objects.get(id=self.request.user.pk)

    def form_valid(self, form):
        messages.set_level(self.request, messages.SUCCESS)
        messages.error(self.request, 'Данные изменены')
        super().form_valid(form)
        return HttpResponseRedirect(self.get_success_url())


class DeleteUserView(DeleteView):
    model = User
    success_url = reverse_lazy('user:login')


class ListUsersView(ListView):
    model = User
    template_name = 'user/list_users.html'
    extra_context = {
        'title': 'Список пользователей сервиса'
    }

    def get_queryset(self):
        return get_users()


class BlockUser(PermissionRequiredMixin, UpdateView):
    permission_required = 'user.can_blocked_user'
    model = User
    form_class = UserBlockedForm
    template_name = 'user/block_user.html'
    extra_context = {
        'title': 'Блокировка пользователя'
    }

    def post(self, request, *args, **kwargs):
        if self.request.method == 'POST':
            user_object = User.objects.get(id=kwargs['pk'])
            user_object.is_active = False
            user_object.save()
            return HttpResponseRedirect(reverse('user:list_users'))

user/templates/user/base.html
{% load static %}


<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>

<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark" aria-label="Main navigation">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'blog:index' %}">Главная страница</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>


        <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                {% if user.is_authenticated %}

                {#
                <li class="nav-item">#}
                    {# <a class="nav-link" href="#">Profile</a>#}
                    {#
                </li>
                #}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Операции
                        с письмами</a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'sending:create_message' %}">Создать письмо</a>
                        </li>
                        <li><a class="dropdown-item" href="{% url 'sending:list_messages' %}">Список писем</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Операции
                        с рассылками</a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'sending:create_sending' %}">Создать рассылку</a>
                        </li>
                        <li><a class="dropdown-item" href="{% url 'sending:list_sending' %}">Список рассылок</a>
                        </li>
                        <li><a class="dropdown-item" href="{% url 'sending:list_try_sending' %}">Отчеты о рассылках</a>
                        </li>

                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown"
                       aria-expanded="false">Клиенты</a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'customer:create_customer' %}">Создать клиента</a>
                        </li>
                        <li><a class="dropdown-item" href="{% url 'customer:list_customers' %}">Список клиентов</a>
                        </li>

                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">{{
                        user.email }}</a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'user:logout' %}">Выйти</a>
                        </li>
                        <li><a class="dropdown-item" href="{% url 'user:profile' %}">Профиль</a>
                        </li>

                    </ul>
                </li>
                <li class="nav-item">
                    <a class="p-2 btn btn-outline-light" href="{% url 'user:list_users' %}">Список пользователей</a>
                </li>
                <li class="nav-item">
                    <a class="p-2 btn btn-outline-light" href="{% url 'blog:list_posts' %}">Блог</a>
                </li>
            </ul>


            {% else %}
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'user:login' %}">Авторизация</a>
            </li>
            {% endif %}
        </div>
    </div>
</nav>

<br>
<br>
<br>
<br>
<br>

{% block content %}
{% endblock %}
<div class="container">
    <footer class="py-3 my-4">

        <p class="text-center text-muted">&copy; 2023 Kisa</p>
    </footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

user/templates/user/block_user.html
{% extends 'user/base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}

    <div class="container">
        <h1 class="text-warning">Блокировка пользователя</h1>
        <form method="POST">
            {% csrf_token %}
            <table>
            Подтвердите блокировку {{ object.email }}
            </table>
            <input class="btn-danger" type="submit" value="Блокировать">
            <a type="button" href="{% url 'user:list_users' %}"
               class="btn btn-lg btn-block btn-link">Назад</a>
        </form>
    </div>
{% endblock %}

user/templates/user/confirm_code.html
{% extends 'user/base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
    <div class="container">
        <div class="col-12">
            <form class="row" method="post">
                {% csrf_token %}
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">
                            <h3>Подтверждение почты</h3>
                        </div>
                        <div class="card-body">
                            <div class="col-auto">
                                <label for="inputPassword6" class="col-form-label">Введите код подтверждения:</label>
                            </div>
                            <div class="col-auto">
                                <input type="text" id="inputPassword6" class="form-control"
                                       aria-labelledby="passwordHelpInline" name="verify_code">
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Отправить</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

user/templates/user/list_users.html
{% extends 'user/base.html' %}

{% block title %} {{ title }} {% endblock %}

{%  block content %}
    <div class="container">
    {% for object in object_list %}
    <div class="row text-center">
                <div class="col-12">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <h4 class="my-0 font-weight-normal">{{ object.first_name }}</h4>
                        </div>
                        <div class="card-body">
                            <ul class="list-unstyled mt-3 mb-4 text-center m-3 bg-light" >
                                <li>Фамилия: {{ object.last_name}}</li>
                            </ul>
                            <a type="button" href="{% url 'user:blocked_user' object.id %}"
                               class="btn btn-lg btn-block btn-danger">Блокировка пользователя</a>
                        </div>
                    </div>
                </div>
            </div>
    {% endfor %}
    </div>
{% endblock %}

user/templates/user/login.html
{% extends 'user/base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
    <div class="container">
        <div class="col-lg-5">
            {% if form.non_field_errors or messages %}
                <div class="alert {% if messages %} alert-success {% else %} alert-warning {% endif %}alert-dismissible fade show"
                     role="alert"
                     style="margin-top: 50px;">
                    {% if messages %}
                        {% for mes in messages %}
                            {{ mes }}
                        {% endfor %}
                    {% else %}
                        {% for error in form.non_field_errors %}
                            {{ error }}
                        {% endfor %}
                    {% endif %}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
            <div class="card shadow-lg border-0 rounded-lg mt-5">
                <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3>
                </div>
                <div class="card-body">
                    <form action="{% url 'user:login' %}" method="post">
                        {% csrf_token %}
                        <table>
                            {{ form.as_table }}
                        </table>
                        <input type="submit" value="Войти">
                    </form>
                </div>
                <div class="card-footer text-center">
                    <div class="small"><a href="{% url 'user:register' %}">Зарегистрируйтесь для доступа к проекту</a></div>
                    <div class="list-group-horizontal card-footer text-center small">
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

user/templates/user/profile.html
{% extends 'user/base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            {% if  messages %}
                <div class="alert {% if messages.level == 25 %} alert-success {% else %} alert-warning {% endif %}alert-dismissible fade show"
                     role="alert"
                     style="margin-top: 50px;">
                    {% if messages %}
                        {% for mes in messages %}
                            {{ mes }}
                        {% endfor %}
                    {% endif %}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
            <h4 class="mt-3 mb-3">Профиль</h4>
            <form action="{% url 'user:profile' %} " method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="img-fluid">
                    <img width="150" height="150"
                         src="{% if user.avatar %} {{ user.avatar.url }} {% else %}Аватар отсутствует {% endif %}"
                         class="rounded float-right">
                </div>
                {{ form.as_p }}
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        <a type="button" href="{% url 'user:delete' object.id %}"
                           class="btn btn-lg btn-block btn-danger">Удалить</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

user/templates/user/register.html
{% extends 'user/base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
    {% if form.errors %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert"
         style="margin-top: 50px;">
        {% for error in form.errors %}
        {{ error | escape }}
        {% endfor %}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}
    <div class="container">
    <form action="{% url 'user:register' %}" method="post">
        {% csrf_token %}

        <div class="form-row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                    {{ form.first_name }}
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                    {{ form.last_name }}
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="col-md-6">
                <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                {{ form.username }}
            </div>
            <div class="col-md-6">
                <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                    почты</label>
                {{ form.email }}
            </div>
        </div>
        <div class="form-row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.password1.id_for_label }}">Пароль</label>
                    {{ form.password1 }}
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.password2.id_for_label }}">Подтверждение
                        пароля</label>
                    {{ form.password2 }}
                </div>
            </div>
        </div>
        <div class="form-group mt-4 mb-0">
            <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
        </div>
    </form>
    </div>
{% endblock %}

user/templates/user/user_confirm_delete.html
{% extends 'user/base.html' %}

{% block content %}
<div class="col">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Удаление профиля</h5>
      <form method="post">
        {% csrf_token %}
        Подтверждаете удаление профиля "{{ object.username }}"?<br>
        <input type="submit" class="btn btn-outline-danger" value="Уверен">
      </form>
      <div class="card-footer">
        <a href="{% url 'user:profile' %}" class="btn btn-primary"><< Отмена</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}